# Generated by Django 3.1.1 on 2021-06-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210601_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
